### ISSUE TITLE
400 error when metric_usage_client is prom analytics proxy

### ISSUE THREAD

**Issue by liaeden100** [perses/metrics-usage#57]
### What did you do?

i have a metrics collector instance connected to my thanos query, and a grafana collector connected to my grafana instance. (url of openshift routes). when i do a get request to /api/v1/metrics i see all the metrics and the usage in dashboard. 
i also have a prom analytics proxy running on open shift. i configured the metrics usage to send the usage to the prom analytics proxy:

config:
   metric_collector:
       enable: true
       http_client:
           url: "<http route to the thanos query>"
   grafana_collector:
       enable: true
       metric_usage_client:
            url: "<http route to the prom analytics proxy>"
       grafana_client:
            url: "<http route of the grafana>"
            basic auth:
             ..... (username and password)

### What did you expect to see?

metrics usage project sends the metrics usage to the prom analytics project and i can see this in the ui.

### What did you see instead? Under which circumstances?

i get an 400 error in metrics usage:

`
msg="Failed to send usage for metric" collector=grafana error="when sending metrics usage, unexpected status code: 400"
`

### MetricsUsage version

0.5.0

### MetricsUsage configuration file

```yaml
config:
   metric_collector:
       enable: true
       http_client:
           url: "<http route to the thanos query>"
   grafana_collector:
       enable: true
       metric_usage_client:
            url: "<http route to the prom analytics proxy>"
       grafana_client:
            url: "<http route of the grafana>"
            basic auth:
             ..... (username and password)
```

### Logs

```text
msg="Failed to send usage for metric" collector=grafana error="when sending metrics usage, unexpected status code: 400"
```
